version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

  jobs:
    pre_build:
      - echo "Installing EvSpikeSim"
      - sudo apt-get install g++ cmake
      - mkdir build
      - cd build
      - cmake ../core -DNO_TEST=ON
      - make -j
      - make install
      - cd ../python_api
      - pip3 install requirements.txt
      - python3 setup.py install --user

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
  - epub