version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.9"

  apt_packages:
    - g++
    - cmake

  jobs:
    pre_build:
      - echo "Installing EvSpikeSim"
      - mkdir build &&
        cd build &&
        cmake ../core -DNO_TEST=ON &&
        make -j
      - cd python_api &&
        pip3 install -r requirements.txt &&
        python3 setup.py install --user

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub