name: C++ Library Tests

on:
  pull_request:
    branches:
    - '*'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  cpp_library_cpu_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Google Test
      run: sudo apt-get install libgtest-dev

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      run: cmake -S core -B build

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: | 
        make tests -j
        sudo make install

    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ./tests/tests
